package de.fhws.simplex;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpSession;
import java.math.BigDecimal;

/**
 * This class functions as the Controller for all the Simplex applications.
 *
 * @author Anton Kaiser, Fabian Struensee
 */
@RestController
public class SimplexController {

    /**
     * This methods enables the subdomain "/home" and enables the server to accept a GET-request
     *
     * @param input   string version of the JSON with normal brackets instead of square brackets
     * @param zeilen  amount of rows in the given matrix
     * @param spalten amount of column in the given matrix
     * @return the matrix object generated by the inputs
     * @author Anton Kaiser
     */
    @GetMapping("/home")
    public Matrix home(@RequestParam("matrix") String input, @RequestParam("zeilen") int zeilen, @RequestParam("spalten") int spalten) {
        Matrix matrix = new Matrix(parseInput(zeilen, spalten, input));
        matrix.printMatrix();
        System.out.println(matrix);
        System.out.println("Hi");
        return matrix;
    }

    /**
     * This methods enables the subdomain "/api/matrix" and enables the server to accept a GET-request with the matrix as a JSON file
     *
     * @param matrix the matrix object generated by the JSON input
     * @return the matrix object generated by the inputs
     * @author Anton Kaiser
     */
    @GetMapping("/api/matrix")
    public Matrix getMatrix(@RequestBody Matrix matrix) {
        return matrix;
    }

    /**
     * Parse String arguments such as ((-300,-500,-36000),(1,2,170),(1,1,150),(0,3,180)) into an actual array
     *
     * @param input   string version of the JSON with normal brackets instead of square brackets
     * @param zeilen  amount of rows in the given matrix
     * @param spalten amount of column in the given matrix
     * @return an array of numbers from the given input
     * @author Anton Kaiser, Fabian Struensee
     */

    public static BigDecimal[][] parseInput(int zeilen, int spalten, String input) {
        BigDecimal[][] array = new BigDecimal[zeilen][spalten];
        String[] temp = input.split(",");
        for (int i = 0; i < temp.length; i++) {
            temp[i] = temp[i].replace("(", "");
            temp[i] = temp[i].replace(")", "");
        }
        for (int column = 0; column < spalten; column++) {
            for (int row = 0; row < zeilen; row++) {
                array[row][column] = BigDecimal.valueOf(Double.parseDouble(temp[row * spalten + column]));
            }
        }

        for (BigDecimal[] list : array) {
            for (BigDecimal b : list) {
                System.out.println(b);
            }
        }

        return array;
    }
}